music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/user.rb
class User < ApplicationRecord

    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}
    attr_reader :password

    after_initialize :ensure_session_token

    def self.generate_session_token
        self.session_token = SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        self.password_digest == BCrypt::Password.create(password)
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        if user != nil
            user.is_password?(password) ? user : nil
        end
        nil
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :current_user_id, :logged_in?

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def current_user_id
        current_user ? current_user.id : nil
    end

    def logged_in?
        !!current_user
    end

    def login_user!(user)
        session[:session_token] = user.reset_session_token!
    end

    def require_user!
        redirect_to new_session_url if current_user.nil?
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )

        if user.nil?
            flash.now[:errors] = ["Invalid credentials"]
            render :new
        elsif !user.activated?
            flash.now[:errors] = ['You must activat your account first! Check your email.']
            render :new
        else
            login_user!(user)
            redirect_to root_url
        end
    end

    def destroy
        current_user.reset_session_token!
        sessionp[:session_token] = nil

        redirect_to new_session_url
    end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        render :show
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            @user.activate!
            login_user!(@user)
            redirect_to root_url
        else
            flash.now[:errors] = @user.full_messages
            render :new
        end
    end

    def activate
        @user = User.find_by(activation_token: params[:activation_token])
        @user.activate!
        login_user!(@user)
        flash[:notice] = 'Successfully activated your account!'
        redirect_to root_url
    end


    private

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1 class ='page-header'>New User</h1>

<a class='button' href=<%= new_session_url %> >Go to sign_in</a>
<form class='form' action="<%= users_url %>" method="post">

<input
type="hidden"
name="authenticity_token"
value="<%= form_authenticity_token %>">

<p>
    <label for='new-user-email'>Email</label>
    <input id='new-user-email' type="text" name="user[email]">
</p>

<p>
    <label for='new-user-password'>Password</label>
    <input id='new-user-password' type="password" name="user[password]">
</p>

<input type="submit" value="Submit">
</form>

music_app/app/views/users/show.html.erb
{\rtf1}